ARG BASE_IMAGE=""

FROM ${BASE_IMAGE} as base

ARG VLLM_COMMITID=""
ARG OAIP_COMMITID=""
ARG IMAGE=""
ARG proxy_val=""

ENV http_proxy=$proxy_val
ENV https_proxy=$proxy_val
ENV DEPLOY_BASE_IMAGE=${BASE_IMAGE}
ENV DEPLOY_IMAGE=${IMAGE}
ENV VLLM_COMMITID=$VLLM_COMMITID
ENV OAIP_COMMITID=$OAIP_COMMITID

WORKDIR /vllm
#fix base image, delete while base image updated
RUN rm /vllm/oaip -r

COPY . .
RUN bash /vllm/thirdparty/install.sh && rm -rf /vllm/thirdparty

#for T4:
#Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
#If this call came from a _pb2.py file, 
#your generated code is out of date and must be regenerated with protoc >= 3.19.0.
RUN pip uninstall protobuf -y && pip install protobuf==3.19.0

ENV http_proxy=""
ENV https_proxy=""